name: DeerLab testsuite
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - uses: actions/cache@v2
        if: startsWith(runner.os, 'Windows')
        with:
          path: |
            ~\pipwin
            ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-${{ hashFiles('**/setup.py') }}
          restore-keys: |
            {{ runner.os }}-pip-

      - uses: actions/cache@v2
        if: startsWith(runner.os, 'macOS')
        with:
          path: |
            ~/Library/Caches/pip
          key: ${{ runner.os }}-${{ hashFiles('**/setup.py') }}
          restore-keys: |
            {{ runner.os }}-pip-

      - uses: actions/cache@v2
        if: startsWith(runner.os, 'Linux')
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-${{ hashFiles('**/setup.py') }}
          restore-keys: |
            {{ runner.os }}-pip-

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'false'
        run: |
          python -m pip install --upgrade pip
          python setup.py install
          python -m pip install pytest
  
      - name: Test with pytest
        run: pytest
