name: Continuous Integration

on: 
   push:
      branches:
      - master
      - develop
      - release

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - name: Checkout trigger commit
      uses: actions/checkout@v1
    - name: Install dependencies
      run: |
           sudo apt-get install -y openvpn openconnect
    - name:Establish VPN connection
      run: |
           # Force returning packets to be routed over public interface and not over the VPN
           sudo ip rule add from $(ip route get 1 | grep -Po '(?<=src )(\S+)') table 128
           sudo ip route add table 128 to $(ip route get 1 | grep -Po '(?<=src )(\S+)')/32 dev $(ip -4 route ls | grep default | grep -Po '(?<=dev )(\S+)')
           sudo ip route add table 128 default via $(ip -4 route ls | grep default | grep -Po '(?<=via )(\S+)')
           # Start network tunnel (TUN) device
           sudo openvpn --mktun --dev tun1
           sudo ifconfig tun1 up
           # Start connection to ETH VPN
           echo ${{ secrets.VPN_PASSWD }} | sudo openconnect ${{ secrets.VPN_SERVER }} --user=${{ secrets.VPN_USER }} --background --passwd-on-stdin
    - name: Transfer source files to CI-server
      run: |
           rm -f -r ./.git
           echo ${{ secrets.GATEWAY_KEY }} > sshkey
           sudo chmod 600 ~/sshkey
           scp -i ~/sshkey -P ${{ secrets.GATEWAY_PORT }} -r ../DeerAnalysis2 ${{ secrets.GATEWAY_HOST }}:/home/lufa/scp_traffic/
           ssh -i ~/sshkey -p ${{ secrets.GATEWAY_PORT }} ${{ secrets.GATEWAY_HOST }} scp -r /home/lufa/scp_traffic/DeerAnalysis2 ${{ secrets.CISERVER_HOST }}:/home/deeranalysis/
           ssh -i ~/sshkey -p ${{ secrets.GATEWAY_PORT }} ${{ secrets.GATEWAY_HOST }} "rm -f -r /home/lufa/scp_traffic/DeerAnalysis2"
    - name: Establish connection to CI-Server
      run: |
           ssh -i ~/sshkey -p ${{ secrets.GATEWAY_PORT }} -t ${{ secrets.GATEWAY_HOST }} ssh ${{ secrets.CISERVER_HOST }}
    - name: Run test suite
      run: |
           #Run test suite
           cd DeerAnalysis2/build
           matlab -nodesktop -r "datestsuite;exit"
           #Transfer log file to the gateway
           scp -i ~/sshkey -P ${{ secrets.GATEWAY_PORT }} ./*_log ${{ secrets.GATEWAY_HOST }}:/home/lufa/scp_traffic/
           #Delete the source files
           cd /home/deeranalysis/
           rm -f -r DeerAnalysis2
    - name: Disconnect CI-server
      run: |
           logout
           #Transfer log file to GitHub VM
           scp -i ~/sshkey -P ${{ secrets.GATEWAY_PORT }}.${{ secrets.GATEWAY_HOST }}:/home/lufa/scp_traffic/*_log ~
           ssh -i ~/sshkey -p ${{ secrets.GATEWAY_PORT }} ${{ secrets.GATEWAY_HOST }} "rm -f /home/lufa/scp_traffic/*_log"
           rm -f ~/sshkey
    - name: Disconnect VPN connection
      run: |
           #Remove TUN device
           sudo ifconfig tun1 down
           sudo openvpn --rmtun --dev tun1
           #Ensure the VPN is disconnected by killing openconnect
           sudo pkill openconnect
    - name: Archive test suite & code coverage results
            uses: actions/upload-artifact@v1
            with:
              name: datestsuite_report
              path: ~/*_log