name: CI

on: [push]

jobs:

  build:
    name: Test suite
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Connect VPN
      run: |
          sudo apt-get update
          sudo apt-get install openconnect lib32ncurses5 lib32tinfo5 lib32z1 libc6-i386 libpkcs11-helper1 openvpn vpnc-scripts net-tools
          sudo openvpn --mktun --dev tun1
          sudo ifconfig tun1 up
          echo ${{ secrets.VPN_PASSWD }} | sudo openconnect --background --user ${{ secrets.VPN_USER }} --authgroup student-net --passwd-on-stdin sslvpn.ethz.ch/student-net

    - name: Action in SSH server
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.EULER_HOST }}
          username: ${{ secrets.EULER_USER }}
          key: ${{ secrets.EULER_KEY}}
          script: |
             ls -al

    - name: Disconnect VPN
      run: |
          sudo pkill -SIGINT openconnect
          sudo ifconfig tun1 down
          sudo ip link delete tun1