name: DeerLab testsuite
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Cache multiple paths
        uses: actions/cache@v2'
        if: startsWith(runner.os, 'Windows')
        with:
          path: |
            ~\pipwin
            ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-${{ hashFiles('**/setup.py') }}
        - name: Install dependencies
          if: steps.cache.outputs.cache-hit != 'true'
          run: |
            python -m pip install --upgrade pip
            python setup.py install
        - name: Test with pytest
          run: pytest -vv
