name: Webpage update

on: 
   push:
      branches:
      - master
      - develop
      paths:
      - 'docsrc/**'
      - '.github/**'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
           python -m pip install --upgrade pip
           python -m pip install sphinx==1.8.0
           python -m pip install sphinx_rtd_theme
           python -m pip install sphinxcontrib-matlabdomain
           python -m pip install sphinxcontrib-httpdomain
           sudo apt install texlive-extra-utils
           sudo apt-get install texlive-latex-extra
           
    - name: Run Sphinx Builder
      run: |
           cd docsrc
           sphinx-build -E -b html ./source ../docs
    - name: Connect and update DeerLab AWS S3 Bucket
      run: |
           cd build
           python -m synchS3 -k ${{ secrets.S3_ACCESS }} -s ${{ secrets.S3_SECRETACCESS }} -d "../docs" --bucket deeranalysis.org