name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Connect to Euler 
      run: ssh luisf@euler.ethz.ch  bash ~/bin/euler_build.bash
    - name: Finish job
      run: |
        echo Successfully completed
