name: test
on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ls -a via OPEN SSH Private Key
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd ~
            ls -a
          host: ${{ secrets.EULER_HOST }}
          user: ${{ secrets.EULER_USER }}
          key: ${{ secrets.EULER_SSH_KEY}}
